set-option -g default-shell "/usr/bin/fish"
set -g default-command "/usr/bin/fish"

# プレフィックスキーの変更
set -g prefix C-Space
unbind C-b

# ペインの分割
bind + split-window -h
bind - split-window -v

# ペインのリサイズ
bind-key -n M-h resize-pane -L 5
bind-key -n M-j resize-pane -D 5
bind-key -n M-k resize-pane -U 5
bind-key -n M-l resize-pane -R 5

# ペインの移動
bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

# シンクロの開始・終了
bind S set-window-option synchronize-panes
bind a set-window-option synchronize-panes on
bind b set-window-option synchronize-panes off

# tmuxの操作をvimキーバインドにする
set-window-option -g mode-keys vi

# tmux status-line
set -g status-fg black
set -g status-bg white

# プラグイン
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'
