set-option -g default-shell "/usr/bin/fish"
set -g default-command "/usr/bin/fish"
set -g default-terminal "xterm-256color"

# change prefixkey
set -g prefix C-s
unbind C-b

# Neovimがフォーカスイベントを正しく受け取れるようにする
set-option -g focus-events on

# split pane
unbind '"'
unbind %
bind + split-window -h
bind - split-window -v

# select pane bind h select-pane -L
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# synchro panes
bind S set-window-option synchronize-panes

# move pane
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

bind C display-popup -E -w 80% -h 80% -d '#{pane_current_path}' "claude-monitor"

set-window-option -g mode-keys vi

set-window-option -g xterm-keys on

set-option -g allow-passthrough on

set-option -g status-position bottom



# List of plugins
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin "catppuccion/tmux#v2.1.3"
set -g @plugin "omerxx/tmux-sessionx"
set -g @plugin "tmux-plugins/tpm"

# sessionx の設定
set -g @sessionx-bind 's'
set -g @sessionx-additional-options "--bind 'tab:replace-query'"

run -b "~/.config/tmux/plugins/tpm/tpm"

# catppuccion theme
set -g @catppuccin_flavor "frappe"
set -g @catppuccin_window_status_style "rounded"

# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
